
server:
  port: 8001

filePath: D:\\temp\\caiwei.mp4


spring:
  application:
    name: caiwei

  #mysql config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.129.1:3306/test?useSSL=false&serverTimezone=CTT&characterEncoding=UTF-8
    username: root
    password: 1518290

  #active mq config
  activemq:
    broker-url: tcp://www.caiwei.ink:61616
    user: admin
    password: admin



